name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag certbot-dns-aliyun:main

    - name: Login to Docker Hub
      run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Tag and Push Docker image
      run: |
        docker tag certbot-dns-aliyun:main aiyax/certbot-dns-aliyun:latest
        docker push aiyax/certbot-dns-aliyun:latest
